name: Deploy Opentofu Project
on:
  workflow_dispatch:

defaults:
  run:
    working-directory: live/dev/s3
    
jobs:
  tofu-apply:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Opentofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.2
          
      - name: OpenTofu fmt
        id: fmt
        run: tofu fmt -check
        continue-on-error: true
        
      - name: OpenTofu Init
        id: init
        run: tofu init
        
      - name: OpenTofu Validate
        id: validate
        run: tofu validate -no-color
      
      - name: OpenTofu Plan
        id: plan
        run: tofu plan -no-color
        continue-on-error: true
