name: Deploy Opentofu Project
on:
  workflow_dispatch:
    
jobs:
  tofu-apply:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.2
